import { useState, useEffect } from 'react';
import './App.css';
import Dashboard from './Dashboard';

function App() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Fetch the JSON generated by the scraper
    fetch('/futbolaragon_data.json')
      .then(res => res.json())
      .then(json => {
        setData(json);
        setLoading(false);
      })
      .catch(err => {
        console.error("Error loading JSON data:", err);
        setLoading(false);
      });
  }, []);

  if (loading) {
    return (
      <div className="loading-screen">
        <div className="spinner"></div>
        <h2>Cargando Estadísticas...</h2>
      </div>
    );
  }

  if (!data) {
    return (
      <div className="error-screen">
        <h2>Error al cargar datos.</h2>
        <p>Asegúrate de que el scraper ha generado el archivo futbolaragon_data.json correctamente.</p>
      </div>
    );
  }

  return (
    <div className="app-container">
      <header className="app-header">
        <h1>📊 Huesca SD - Dashboard Analítico</h1>
        <p>Estadísticas completas de la temporada actual</p>
      </header>
      <main className="app-main">
        <Dashboard data={data} targetPlayer="JAIME LOUREDA ALVAREZ" />
      </main>
    </div>
  );
}

export default App;
